### ISSUE TITLE
Chairs with different orientations have same basis Scene_00000

### ISSUE THREAD

**Issue by micaeltchapmi** [bertjiazheng/Structured3D#10]
Hi,

Thanks for this great dataset. I found out that the basis of the 3D bounding boxes (obtained from bbox_3d.json) of the two opposite facing chairs in Scene_00000 with instance ID's->(59,60) gotten from instance.png are the same. Could this be an error in the annotation?

**Comment by bertjiazheng** [comment]
Hi @micaeltchapmi 

Indeed this is a bug. Thanks for your comments. We found a bug when extracting the _basis_ from the transformation. Here is the fixed one (the green denotes the front side):

![fixed](https://user-images.githubusercontent.com/8075304/77532479-e22b5e00-6ecf-11ea-897b-b0e6292e6f86.png)

We will update these annotations ASAP.

Best,
Jia

**Comment by bertjiazheng** [comment]
We uploaded the fixed annotations. If you have any other questions, feel free to re-open this issue. 

Best,
Jia

**Comment by Xia0ben** [comment]
Hi,
I have just found the same issue (same scene, same misoriented objects) on the dataset I downloaded last week, are you sure the fixed annotations have been uploaded ?

**Comment by bertjiazheng** [comment]
I am currently involved in another project, will check this issue.

**Comment by bertjiazheng** [comment]
Hi @Xia0ben 

I have checked the 3D bounding box annotation. The chair orientation is correct.

**Comment by Xia0ben** [comment]
Hi @bertjiazheng ,

Here are images of the bounding boxes data for Scene 00000 I got when I downloaded two week ago: 

![img1](https://user-images.githubusercontent.com/10845530/92097310-379d5c80-edd8-11ea-8017-f9b056c42aea.png)
![img2](https://user-images.githubusercontent.com/10845530/92097312-3835f300-edd8-11ea-802a-3fef0cd5de6a.png)

Color legend of boxes faces :
Top=red, bottom=blue, back=grey, front=yellow, right=purple, left=green.

In the images, both chairs have their colors oriented in the same direction, and it seems that all the objects in the kitchen have the same orientation, which is weird (especially for the furniture which should have its back to the walls ?). Otherwise, in the other rooms, the orientations seem fine (eg. the bed is correctly oriented, for example).

Would you mind sending me the bbox_3d.json file for scene 00000 that you used to check please ? This way, I could determine if the fault lies somewhere in the bit of code I wrote to display the bounding boxes, or if we just had a different version of the data ?

Otherwise, I'd be willing to send you by email an archive with my Jupyter Notebook and scene data used ?

Wish you a pleasant day !

**Comment by bertjiazheng** [comment]
Can you draw these two chairs in 2D to give a quick check that you used the right annotation?

> Hi @micaeltchapmi
> 
> Thanks for your comments. Indeed this is a bug. We found a bug when extracting the _basis_ from the transformation matrix.
> 
> Before (the green denotes the front side):
> ![before](https://user-images.githubusercontent.com/8075304/77609412-dd5fbc00-6f5a-11ea-846d-c5972944823d.png)
> and the one with fixed basis:
> ![after](https://user-images.githubusercontent.com/8075304/77532660-3cc4ba00-6ed0-11ea-8673-e51396da85f5.png)
> 
> We will update these annotations ASAP.
> 
> Best,
> Jia

**Comment by Xia0ben** [comment]
Hi @bertjiazheng ,
Is there a piece of code that can generate these exact images in the repository ? If not, could you please send me the one you used ?

**Comment by bertjiazheng** [comment]
You can adopt visualize_bbox.py and only show these two chairs with ids (59,60).

Replace these two lines (https://github.com/bertjiazheng/Structured3D/blob/master/visualize_bbox.py#L62_L63) with the following codes:
`
for i in range(num_corner//2):
    plt.plot(gt2dcorners[0, [i, i + num_corner]], gt2dcorners[1, [i, i + num_corner]], 'y')
for i in range(num_corner//2, num_corner):
    plt.plot(gt2dcorners[0, [i, i + num_corner]], gt2dcorners[1, [i, i + num_corner]], 'g')
`

**Comment by Xia0ben** [comment]
Hi again !

So here are the three kitchen images generated for scene 00000:

![Figure_1](https://user-images.githubusercontent.com/10845530/92102742-46d3d880-eddf-11ea-9654-fcf951edd4d3.png)
![Figure_1-1](https://user-images.githubusercontent.com/10845530/92102746-476c6f00-eddf-11ea-8860-f5c604ce6bb3.png)
![Figure_1-2](https://user-images.githubusercontent.com/10845530/92102747-476c6f00-eddf-11ea-8ade-819aedf9ac3a.png)

It seems that they the chairs are properly oriented in these, so I guess the error must lie in my interpretation of the bounding boxes data ?

**Comment by Xia0ben** [comment]
Here the filtered results with just the chairs:
![Figure_1-3](https://user-images.githubusercontent.com/10845530/92103203-e85b2a00-eddf-11ea-9416-661baf9dd261.png)
![Figure_1-4](https://user-images.githubusercontent.com/10845530/92103204-e8f3c080-eddf-11ea-846f-af6c6cf72a6a.png)
![Figure_1-5](https://user-images.githubusercontent.com/10845530/92103205-e98c5700-eddf-11ea-91c4-9006988e5fa2.png)

So yeah, seems like the data is fine, mybad =).

**Comment by bertjiazheng** [comment]
You can check your code first. If you have any further questions, feel free to reopen this issue.
