### ISSUE TITLE
Semantic annotation for bounding boxes?

### ISSUE THREAD

**Issue by neyrinck** [bertjiazheng/Structured3D#13]
Hi, great dataset! I was wondering if the object semantic annotations, currently only in semantic.png files it seems, could somehow be inferred from the 3D bounding box id's in bbox_3d.json, or in any other 3D data? If not, could this easily be added? Thank you!!!

**Comment by bertjiazheng** [comment]
Hi, @neyrinck 

Currently, the semantic annotations only saved in the _semantic.png_. You can get infer the semantic label for the 3D bounding box from _semantic.png_ and _instance.png_ in the perspective images. 

Best,
Jia

**Comment by neyrinck** [comment]
Thanks! And from the panoramic images, too, which is easier!

**Comment by bertjiazheng** [comment]
The current version of the dataset does not include _instance.png_ for the panoramic images, but we are currently working on it. Hope this helps.

**Comment by neyrinck** [comment]
Ah right, thank you ... but sorry if I am missing something: is
instance.png necessary for inferring the semantic labels? I imagined I
could just ignore wall/floor categories from semantic.png.

**Comment by bertjiazheng** [comment]
You could get an accurate label for each 3D bounding box with the instance label. Without instance label, the semantic label can be determined by the majority voting within each bounding box.

**Comment by Xia0ben** [comment]
Hi @bertjiazheng !

Great dataset indeed ! I ended up finding the same issue when exploring the data : having semantic labels directly associated with the 3D bounding boxes would be so much more helpful ! Especially since it would likely be more accurate to do the association from the source data you used for producing the dataset than inferring it from panoramic pictures (that may hide much of the information because of object occlusion). Also, I could not find any instance.png files in the whole dataset I got to download, which makes the endeavour of doing this quite cumbersome on the end user side.

As far as you know, has any user tried to do this completely ? @neyrinck, @micaeltchapmi, did any of you succeed in computing this inference ?

Could you please consider providing these annotations ? This would really help in working with the dataset, and would not require any new information in itself.

Thank you very much for your time and consideration.
