### ISSUE TITLE
Generating Top Down Layout

### ISSUE THREAD

**Issue by jaidevshriram** [bertjiazheng/Structured3D#23]
Hey,

I am currently trying to use Structured3D for a top-down layout estimation task. Is there a way to generate top-down layout maps like the ones below for Structured 3D? I think a 3D reconstruction using the panoramas would be quite sparse. Note that the top down layout includes information about obstacles, making it different from a floorplan. Any help would be appreciated. Thanks!

![5](https://user-images.githubusercontent.com/29925421/150579927-44481eef-ae09-475a-907a-f0df1a9ffc71.png)
![212](https://user-images.githubusercontent.com/29925421/150579974-adeefb25-f7ac-4d5d-acef-5a6efeb01f21.png)

**Comment by bertjiazheng** [comment]
Hi, 

This can be realized by floorplan with bounding box annotations. You can regard the objects that are more than a given height threshold as obstacles and project the bounding box to the ground floor. However, this approach only generates a box-shaped obstacle, instead of an L-shaped one (shown in your provided figure).

Best,
Jia
